#!/bin/sh -e

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"

REQUIREMENTS="requirements.txt"
VENV="venv"

set -x

if [ -z "$CI_JOB_ID" ]; then
    if [ ! -d "$VENV" ]; then
        "$PYTHON" -m venv "$VENV"
    fi
    PIP="$VENV/bin/pip"
else
    PIP="pip"
fi

"$PIP" install -U -r "$REQUIREMENTS"
