#!/bin/sh -e

export PREFIX=""
if [ -z "$CI_JOB_ID" ] && [ -d 'venv' ]; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}autoflake --in-place --recursive --exclude "venv" .
${PREFIX}black --line-length=99 .
${PREFIX}isort --multi-line=3 --balanced --trailing-comma --force-grid-wrap=0 --combine-as --skip "venv" .
